travis:
  secure:
    BINSTAR_TOKEN: IN+HOhoW3Wdv40Wx7+hvfZJdYjvZSZh5VGRsRLr0q9SopEoURFMRaTGjDlnfbZXBdAnbl8+5qAMmegymtMamsmqWYXWayLFuSDCxtpFmzanROSksA4o59jrtzt24Rya25tymaT4Z2rzLwMrBujlgvPP0dv9LMD5u/rVUJUwzSB7R+bZGCQutFemDIe0jELlk71ESL1peoZ/3/16zke31cn2m/em+kxd94bZFRLVmGJKh6wjTNMLurvuVyDgY2dbox9lDJkKEB1qmrxjuzGvxgKIr/Jq0R1Zsg5TH+Z2nwxIvID3Ywfumr+10M1oyuIdxGVT5xDu0Zw4WX7wGv0gjiVze5IK12oMuCmemwj1TQRTD8FXsz/0n26msYfBxXtatZWe5iDl34tkAR+ha/mKkMzh9qU9zyzyIkwxd/BDqwgTyJMSySbp9Apc12+ufzOnjed5hE/uGLkj/bUkk72qXzmGmYFoV1afcjsN1RzmpublnqvGMc95OD1WOqyFPRenEXLT8xJ+cZqjBZdQg0rAuac0sL6MQ123FEsBadgSNCQZWopzPcbePr9D2nljKl4IxtYZPizEnfb09PG1ghwE+QQGeypqU5/Qt8Lx52Rry5UTaR5IgS1ap3U2TupYIjE8cGgyReXEk6mt/+i70RJtCOc355jw1bQ1qCI/MXM1d6Jc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
